import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn } from "@clerk/nextjs";
import Nav from "@/components/Nav";
import SideBar from "@/components/SideBar";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import RootLayoutClient from "@/components/RootLayoutClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={` relative ${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/logo.png')] bg-no-repeat bg-center bg-cover md:bg-contain min-h-screen`}
        >
          <div className="absolute inset-0 bg-white/40 -z-30"></div>
          <RootLayoutClient>
            <Nav />
            <SideBar />
            {children}

          </RootLayoutClient>
        </body>
      </html>
    </ClerkProvider>
  );
}
